#!/usr/bin/env bash
# Download MariaDB official binary tarball, initialize a datadir under $HOME (no root).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/user_mariadb_env.sh"

mkdir -p "$MARIADB_INSTALL_ROOT" "$MARIADB_STATE_ROOT"

if [[ ! -x "$MARIADB_BASE/bin/mysqld" ]]; then
  mkdir -p "$(dirname "$MARIADB_TARBALL")"
  _have_bytes=0
  if [[ -f "$MARIADB_TARBALL" ]]; then
    _have_bytes="$(stat -c%s "$MARIADB_TARBALL" 2>/dev/null || echo 0)"
  fi
  if [[ "$_have_bytes" -ne "$MARIADB_TARBALL_EXPECTED_BYTES" ]]; then
    echo "==> Downloading MariaDB ${MARIADB_VERSION} (~330MB, resumable) …"
    curl -fL --retry 3 --retry-delay 2 -C - -o "$MARIADB_TARBALL" "$MARIADB_DOWNLOAD_URL"
  else
    echo "==> Using complete tarball: $MARIADB_TARBALL"
  fi
  echo "==> Extracting to $MARIADB_INSTALL_ROOT …"
  tar -xzf "$MARIADB_TARBALL" -C "$MARIADB_INSTALL_ROOT"
else
  echo "==> Using existing MariaDB tree: $MARIADB_BASE"
fi

if [[ ! -x "$MARIADB_BASE/bin/mysqld" ]]; then
  echo "Missing mysqld under $MARIADB_BASE" >&2
  exit 1
fi

INSTALL_DB=()
if [[ -x "$MARIADB_BASE/bin/mariadb-install-db" ]]; then
  INSTALL_DB=( "$MARIADB_BASE/bin/mariadb-install-db" )
elif [[ -f "$MARIADB_BASE/scripts/mariadb-install-db" ]]; then
  INSTALL_DB=( /usr/bin/env bash "$MARIADB_BASE/scripts/mariadb-install-db" )
else
  echo "Cannot find mariadb-install-db in tarball." >&2
  exit 1
fi

if [[ ! -d "$MARIADB_DATADIR/mysql" ]]; then
  echo "==> Initializing datadir: $MARIADB_DATADIR"
  mkdir -p "$MARIADB_DATADIR"
  "${INSTALL_DB[@]}" --datadir="$MARIADB_DATADIR" --basedir="$MARIADB_BASE" \
    --auth-root-authentication-method=normal
else
  echo "==> Datadir already initialized: $MARIADB_DATADIR"
fi

cat > "$MARIADB_CONF" <<EOF
[mysqld]
basedir=${MARIADB_BASE}
datadir=${MARIADB_DATADIR}
socket=${MARIADB_SOCKET}
port=${MARIADB_PORT}
bind-address=127.0.0.1
local_infile=1
skip-external-locking

[client]
socket=${MARIADB_SOCKET}
port=${MARIADB_PORT}
EOF

cat > "$MARIADB_STATE_ROOT/env.sh" <<EOF
# Generated by install_mariadb_no_sudo.sh
export MARIADB_VERSION="${MARIADB_VERSION}"
export MARIADB_INSTALL_ROOT="${MARIADB_INSTALL_ROOT}"
export MARIADB_STATE_ROOT="${MARIADB_STATE_ROOT}"
export MARIADB_BASE="${MARIADB_BASE}"
export MARIADB_DATADIR="${MARIADB_DATADIR}"
export MARIADB_SOCKET="${MARIADB_SOCKET}"
export MARIADB_PORT="${MARIADB_PORT}"
export MARIADB_CONF="${MARIADB_CONF}"
export MARIADB_TARBALL="${MARIADB_TARBALL}"
export MARIADB_DOWNLOAD_URL="${MARIADB_DOWNLOAD_URL}"
EOF

echo
echo "Done. Config: $MARIADB_CONF"
if ldd "$MARIADB_BASE/bin/mysqld" 2>/dev/null | grep -q "not found"; then
  echo
  echo "Warning: some shared libraries are missing. If mysqld fails to start, you may need"
  echo "  libaio1 / libncurses / libtinfo (normally: sudo apt install libaio1)."
  echo
fi
echo "Next: bash $SCRIPT_DIR/start_mariadb_user.sh"
